name: Sync (/ to adamlui/chatgpt-apps/googlegpt/) && (/greasemonkey/ to adamlui/userscripts/chatgpt/googlegpt/)

on:
  push:
    branches: [ master, main ]
    paths:
      - '**'

jobs:
  build:
    if: (github.repository == 'KudoAI/googlegpt') && (github.event.commits[0].committer.username != 'kudo-sync-bot')
    runs-on: ubuntu-latest
    steps:

      - name: Checkout kudoai/googlegpt
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: kudoai/googlegpt
          path: kudoai/googlegpt
          fetch-depth: 2

      - name: Checkout adamlui/chatgpt-apps
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-apps
          path: adamlui/chatgpt-apps

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Sync docs between root & /greasemonkey
        run: |
          shopt -s globstar
          cd ${{ github.workspace }}/kudoai/googlegpt
          for file in docs/**/*.md; do
            relative_path=${file#"docs/"}
            root_doc="${{ github.workspace }}/kudoai/googlegpt/docs/$relative_path"
            gm_doc="${{ github.workspace }}/kudoai/googlegpt/greasemonkey/docs/$relative_path"
            root_modified=$(git log -1 --format="%ct" -- "$root_doc")
            gm_modified=$(git log -1 --format="%ct" -- "$gm_doc")
            if (( root_modified > gm_modified )); then
              cp -f "$root_doc" "$gm_doc"
            else
              cp -f "$gm_doc" "$root_doc"
            fi
          done

      - name: Sync / to adamlui/chatgpt-apps/googlegpt/
        run: |
          rsync -avhr --delete --exclude={'.*','package*json'} \
            ${{ github.workspace }}/kudoai/googlegpt/ \
            ${{ github.workspace }}/adamlui/chatgpt-apps/googlegpt/

      - name: Sync /greasemonkey/ to adamlui/userscripts/chatgpt/googlegpt/
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/kudoai/googlegpt/greasemonkey/ \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/googlegpt/

      - name: Push to kudoai/googlegpt
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@kudoai.com
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `kudoai/googlegpt`]'
          file_pattern: '**'
          repository: kudoai/googlegpt

      - name: Push to adamlui/chatgpt-apps
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@kudoai.com
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `kudoai/googlegpt`]'
          file_pattern: 'googlegpt/**'
          repository: adamlui/chatgpt-apps

      - name: Push to adamlui/userscripts
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@kudoai.com
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `kudoai/googlegpt`]'
          file_pattern: 'chatgpt/googlegpt/**'
          repository: adamlui/userscripts
